### ISSUE TITLE
Let Ms. Writhing be consistent with vanilla relic "onUnequip" logic

### ISSUE THREAD

**Issue by SodiumCyanide** [chaofan-stsmods/chaofanmod#1]
**In `io.chaofan.sts.chaofanmod.relics.MsWrithing.java`:**

Line 80-88:
Ms. Writhing **firstly disables the chosen relic, then call `disableByMsWrithing()` method to notify if that relic is `DisableRelic`**.
However, if executed in that order, that notified relic was unaware of its position in player's relic list.
In the vanilla logic, relics are notified (by calling `onUnequip()`) **before** they are removed from player's relic list.

To resolve this issue, change execution order to **firstly call `disableByMsWrithing()` method to notify if the chosen relic is `DisableRelic`, then disables that relic**.

**Comment by herbix** [comment]
Fixed in https://github.com/chaofan-stsmods/chaofanmod/commit/0aaf4693dd9a820ec68a291c0cccefc9647e6802
